### ISSUE TITLE
TODO: Add streaming actions

### ISSUE THREAD

**Issue by anzev** [xflows/clowdflows-webapp#1]
Add support for working with streaming widgets:
- [ ] add ability to stop/start workflows with streaming widgets
- [ ] streaming workflow detail page
- [ ] streaming widget results view
